name: Dev Build & Deploy

on:
  workflow_call:
    secrets:
      ARTIFACTORY_TOKEN:
        required: true
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        required: true
      UPDATE_MANIFEST_TOKEN:
        required: true
    inputs:
      ARTIFACTORY_REGISTRY:
        required: true
        type: string
      APPS:
        required: true
        type: string
      DOCKER_REPO:
        required: true
        type: string
      PYTHON_VERSION:
        default: "3.11"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_IDENTITY_TOKEN: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
  POETRY_HTTP_BASIC_P6M_AI_PLATFORM_PYPI_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  POETRY_HTTP_BASIC_P6M_AI_PLATFORM_PYPI_PASSWORD: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
  UPDATE_MANIFEST_TOKEN: ${{ secrets.UPDATE_MANIFEST_TOKEN }}
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
  ARTIFACTORY_REGISTRY: ${{ inputs.ARTIFACTORY_REGISTRY }}
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}
  AWS_REGION: ${{ inputs.AWS_REGION }}
  AWS_DEFAULT_OUTPUT: json
jobs:
  build-and-publish:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      # Required for Multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      ##########

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.PYTHON_VERSION }} # Specify your Python version
      - name: Install Poetry
        run: |
          pip install poetry
      
      - name: Create lock file
        run: |
          poetry lock
      # - name: Test
      #   run: |
      #     poetry run pytest # or any other command to run your tests

      - name: Get Package Version
        id: pkg-version
        run: |
          echo "VERSION=$(poetry version --short)" >> $GITHUB_OUTPUT

      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      - name: Set up environment variable
        run: echo "REPO_NAME=$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTION_ROLE_ARN }}
          role-session-name: docker-build
          aws-region: us-east-2
      - uses: aws-actions/amazon-ecr-login@v1
      - uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: "${{ env.REPO_NAME }}-server"
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ steps.ecr.outputs.repository-uri }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ steps.pkg-version.outputs.VERSION }},enable=${{ github.event_name != 'pull_request' }}
            type=sha

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          pull: true
          push: true
          platforms: linux/amd64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            pypi_username=${{ secrets.ARTIFACTORY_USERNAME }}
            pypi_password=${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Record Summary
        run: |
          echo "### Docker Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

      - name: Trigger Update Image Digest
        if: github.ref == 'refs/heads/main'
        run: |
          echo github.ref= ${{ github.ref }}
          echo digest = ${{ steps.build-push.outputs.digest }}
          echo platform_dispatch_url = ${{ vars.PLATFORM_DISPATCH_URL }}
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.UPDATE_MANIFEST_TOKEN }}" \
            ${{ vars.PLATFORM_DISPATCH_URL }} \
            --fail-with-body \
            -d "{\"event_type\": \"update-digest\", \"client_payload\": {\"repository\": \"${GITHUB_REPOSITORY}\", \"registry\": \"ecr\", \"account_id\": \"${{ vars.AWS_ACCOUNT_ID }}\", \"region\": \"us-east-2\", \"directory_name\": \"$(basename ${GITHUB_REPOSITORY})\", \"environment_dir\": \"dev\", \"digest\": \"${{ steps.build-push.outputs.digest }}\"}}"
