name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Corresponds to Artifactory Project or Cloudsmith repo name.'
        required: false
        type: string
        default: ${{ github.repository_owner }}
      deploy:
        description: 'A value indicating whether to push out the Helm chart and bump the version.'
        required: false
        type: boolean
        default: false
    secrets:
      ARTIFACTORY_USERNAME:
        description: 'Artifactory Username'
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        description: 'Artifactory Identity Token'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Artifactory Docker Repository
        uses: docker/login-action@v2
        with:
          registry: p6m.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Helm Package
        run: helm package .

      - name: Get Current Version
        id: current_version
        run: |
          VERSION=$(cat Chart.yaml | grep -e "^version: " | cut -d" " -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Helm Push
        if: ${{ inputs.deploy }}
        run: helm push ${{ github.event.repository.name }}-${{ steps.current_version.outputs.version }}.tgz  oci://p6m.jfrog.io/${{ inputs.namespace }}-docker

      - name: Automated Version Bump
        run: |
          pipx install pybump
          pybump bump --file ./Chart.yaml --level patch

      - name: Commit and Push
        if: ${{ inputs.deploy }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] Bump Version"
          git push
